# Generated by Django 2.2.4 on 2020-07-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.IntegerField(verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('username', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='手机号')),
                ('password', models.CharField(max_length=5, verbose_name='验证码')),
                ('last_send_code', models.IntegerField(default='0', verbose_name='最后一次发送验证码时间戳')),
            ],
            options={
                'verbose_name': '用户个人信息',
                'verbose_name_plural': '用户个人信息',
            },
        ),
    ]
