# Generated by Django 2.2.4 on 2020-07-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(max_length=20, verbose_name='课程ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='课程标题')),
                ('description', models.CharField(max_length=300, verbose_name='课程描述')),
                ('length', models.IntegerField(verbose_name='课程长度')),
                ('path', models.CharField(max_length=500, verbose_name='课程源地址')),
                ('image', models.CharField(max_length=500, verbose_name='图片源地址')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
    ]
