# Generated by Django 2.2.4 on 2020-07-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(verbose_name='课程ID'),
        ),
    ]
