# Generated by Django 2.2.4 on 2020-07-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='study_log',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('last_log', models.IntegerField(verbose_name='最后学习时长')),
                ('last_study', models.IntegerField(verbose_name='最后一次学习时间戳')),
                ('user', models.IntegerField(verbose_name='用户')),
                ('course', models.IntegerField(verbose_name='最后一次学习的课程')),
            ],
            options={
                'verbose_name': '学习记录',
                'verbose_name_plural': '学习记录',
            },
        ),
    ]
